### ISSUE TITLE
Error: ENOENT: no such file or directory, open '.atom\packages\clojure-plus\lib\clj\check_deps.clj'

### ISSUE THREAD

**Issue by rsrini7** [mauricioszabo/clojure-plus#19]
I am using windows 10 atom and i am getting below error. The error occured when i save the clojure file.

Error: ENOENT: no such file or directory, open 'C:\Users\RSrini\undefined\.atom\packages\clojure-plus\lib\clj\check_deps.clj'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at CljCommands.module.exports.CljCommands.getFile (file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clj-commands.coffee:130:8)
    at CljCommands.module.exports.CljCommands.prepare (file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clj-commands.coffee:29:13)
    at CljCommands.module.exports.CljCommands.runRefresh (file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clj-commands.coffee:37:6)
    at file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clojure-plus.coffee:117:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1144:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1114:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\text-editor.js:904:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\pane.js:738:18)
    at Pane.saveItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\workspace.js:693:35)
    at atom-workspace.core:save (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:3:59)

**Comment by rsrini7** [comment]
I did update today and tried. no such file or directory error from different location. Please check below stack trace.

Error: ENOENT: no such file or directory, open 'C:\Users\RSrini\AppData\Local\atom\app-1.13.1\undefined\.atom\packages\clojure-plus\lib\clj\__check_deps__.clj'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at CljCommands.module.exports.CljCommands.getFile (file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clj-commands.coffee:130:8)
    at CljCommands.module.exports.CljCommands.prepare (file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clj-commands.coffee:29:13)
    at CljCommands.module.exports.CljCommands.runRefresh (file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clj-commands.coffee:37:6)
    at file:///C:/Users/RSrini/.atom/packages/clojure-plus/lib/clojure-plus.coffee:121:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1144:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1114:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\text-editor.js:904:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\pane.js:738:18)
    at Pane.saveItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\workspace.js:693:35)
    at atom-workspace.core:save (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:3:59)

**Comment by mauricioszabo** [comment]
Yeah, probably some strange way that Windows handles paths (I only use Linux do develop in Clojure). Probably the error is along these lines: https://github.com/mauricioszabo/clojure-plus/blob/master/lib/clj-commands.coffee#L128

I'll try to look at it

**Comment by mauricioszabo** [comment]
Probably will be fixed by https://github.com/mauricioszabo/clojure-plus/pull/20.

I'll publish version 0.2.3 now, see it fixes your problem.

**Comment by rsrini7** [comment]
Yes @mauricioszabo . No errors now. Thanks.
