### ISSUE TITLE
Uncaught ReferenceError: protoRepl is not defined

### ISSUE THREAD

**Issue by kpnolan** [mauricioszabo/clojure-plus#27]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [clojure-plus](https://github.com/mauricioszabo/clojure-plus) package 0.3.0

### Stack Trace

Uncaught ReferenceError: protoRepl is not defined

```
At /Users/mike/.atom/packages/clojure-plus/lib/clojure-plus.coffee:386

ReferenceError: protoRepl is not defined
    at Object.getCommands (/packages/clojure-plus/lib/clojure-plus.coffee:386:51)
    at /packages/clojure-plus/lib/js/main.js:2003:360
    at /packages/clojure-plus/lib/js/main.js:2061:3)
    at Module.get_Module._compile (/private/var/folders/lp/qbg_t9hn5dq1xwf0xst52xx80000gn/T/AppTranslocation/BCE25115-61CB-4DFD-9383-4447AE21B5D0/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/lp/qbg_t9hn5dq1xwf0xst52xx80000gn/T/AppTranslocation/BCE25115-61CB-4DFD-9383-4447AE21B5D0/d/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (private/var/folders/lp/qbg_t9hn5dq1xwf0xst52xx80000gn/T/AppTranslocation/BCE25115-61CB-4DFD-9383-4447AE21B5D0/d/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/private/var/folders/lp/qbg_t9hn5dq1xwf0xst52xx80000gn/T/AppTranslocation/BCE25115-61CB-4DFD-9383-4447AE21B5D0/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/clojure-plus/lib/clojure-plus.coffee:13:3
```

### Commands

```
```

### Non-Core Packages

```
clojure-indent 0.2.0 
clojure-plus 0.3.0 
```

**Comment by mauricioszabo** [comment]
Clojure-plus depends of proto-repl. I'll explicitly add this dependency, but for now, try installing proto-repl and see if it works.

**Comment by skyperx** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0-beta0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [clojure-plus](https://github.com/mauricioszabo/clojure-plus) package 0.3.0


### Stack Trace

Uncaught ReferenceError: protoRepl is not defined

```
At C:\Users\TOSHIBA\.atom\packages\clojure-plus\lib\clojure-plus.coffee:386

ReferenceError: protoRepl is not defined
    at Object.getCommands (/packages/clojure-plus/lib/clojure-plus.coffee:386:51)
    at /packages/clojure-plus/lib/js/main.js:2003:360
    at /packages/clojure-plus/lib/js/main.js:2061:3)
    at /packages/clojure-plus/lib/js/main.js:2063:3)
    at Module.get_Module._compile (~/AppData/Local/atom-beta/app-1.48.0-beta0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom-beta/app-1.48.0-beta0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-beta/app-1.48.0-beta0/resources/app/static/<embedded>:11:146819)
    at /packages/clojure-plus/lib/clojure-plus.coffee:13:3
```

### Commands

```
  2x -0:51.9.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-ansible 0.1.25 
brackets 0.5.0 
busy-signal 2.0.1 
c-header-generator 0.2.0 
clojure-color-scope-syntax 1.0.2 
clojure-lsp-adapter 0.1.0 
clojure-party-repl 1.1.0 
clojure-plus 0.3.0 
code-time 4.1.5 
g-code 1.1.0 
header-42 0.3.3 
hey-pane 1.2.0 
hide-files 0.3.0 
html-presets 1.1.2 
Hydrogen 2.14.1 
kite 0.184.0 
language-biicode 0.3.0 
language-c3e 1.0.0 
language-cup 1.1.2 
language-gcode-fff 0.3.2 
language-hcl 0.4.0 
language-trf 0.7.0 
my-package 0.0.0 
scroll-through-time 0.3.1 
switch-header-source 0.34.2 
teletype 0.13.4 
ti-code-fetch 0.4.0 
zentabs 0.8.9 
```

**Comment by mauricioszabo** [comment]
As I told before:

> Clojure-plus depends of proto-repl. I'll explicitly add this dependency, but for now, try installing proto-repl and see if it works.

Closing it for now...
